version: "2"
services:
  kafka1:
    image: 'bitnami/kafka:latest'
    container_name: kafka1
    ports:
      - 9192:9092
      - 9193:9093
    environment:
    ### 通用配置
    # 允许使用kraft，即Kafka替代Zookeeper
      - KAFKA_ENABLE_KRAFT=yes
    # kafka角色，做broker，也要做controller
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
    # 指定供外部使用的控制类请求信息
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    # 定义kafka服务端socket监听端口
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
    # 定义安全协议
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    # 使用Kafka时的集群id，集群内的Kafka都要用这个id做初始化，生成一个UUID即可
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
    # 集群地址
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
    # 允许使用PLAINTEXT监听器，默认false，不建议在生产环境使用
      - ALLOW_PLAINTEXT_LISTENER=yes
    ### broker配置
    # 定义外网访问地址（宿主机ip地址和端口）
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://10.1.1.209:9192
    # broker.id，必须唯一
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_NUM_PARTITIONS=12
    volumes:
      - ./kafka_0_data:/bitnami/kafka
    networks:
        - kafka-net
  kafka2:
    image: 'bitnami/kafka:latest'
    container_name: kafka2
    networks:
        - kafka-net
    ports:
      - 9292:9092
      - 9293:9093
    environment:
    ### 通用配置
    # 允许使用kraft，即Kafka替代Zookeeper
      - KAFKA_ENABLE_KRAFT=yes
    # kafka角色，做broker，也要做controller
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
    # 指定供外部使用的控制类请求信息
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    # 定义kafka服务端socket监听端口
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
    # 定义安全协议
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    # 使用Kafka时的集群id，集群内的Kafka都要用这个id做初始化，生成一个UUID即可
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
    # 集群地址
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
    # 允许使用PLAINTEXT监听器，默认false，不建议在生产环境使用
      - ALLOW_PLAINTEXT_LISTENER=yes
    ### broker配置
    # 定义外网访问地址（宿主机ip地址和端口）
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://10.1.1.209:9292
    # broker.id，必须唯一
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_NUM_PARTITIONS=12
    volumes:
      - ./kafka_1_data:/bitnami/kafka
  kafka3:
    image: 'bitnami/kafka:latest'
    networks:
        - kafka-net
    container_name: kafka3
    ports:
      - 9392:9092
      - 9393:9093
    environment:
    ### 通用配置
    # 允许使用kraft，即Kafka替代Zookeeper
      - KAFKA_ENABLE_KRAFT=yes
    # kafka角色，做broker，也要做controller
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
    # 指定供外部使用的控制类请求信息
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_NUM_PARTITIONS=12
    # 定义kafka服务端socket监听端口
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
    # 定义安全协议
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    # 使用Kafka时的集群id，集群内的Kafka都要用这个id做初始化，生成一个UUID即可
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
    # 集群地址
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
    # 允许使用PLAINTEXT监听器，默认false，不建议在生产环境使用
      - ALLOW_PLAINTEXT_LISTENER=yes
    ### broker配置
    # 定义外网访问地址（宿主机ip地址和端口）
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://10.1.1.209:9392
    # broker.id，必须唯一
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_NODE_ID=3
    volumes:
      - ./kafka_2_data:/bitnami/kafka
  kafka4:
    image: 'bitnami/kafka:latest'
    networks:
        - kafka-net
    container_name: kafka4
    ports:
      - 9492:9092
      - 9493:9093
    environment:
    ### 通用配置
    # 允许使用kraft，即Kafka替代Zookeeper
      - KAFKA_ENABLE_KRAFT=yes
    # kafka角色，做broker，也要做controller
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
    # 指定供外部使用的控制类请求信息
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_NUM_PARTITIONS=12
    # 定义kafka服务端socket监听端口
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
    # 定义安全协议
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093,4@kafka4:9092
    # 使用Kafka时的集群id，集群内的Kafka都要用这个id做初始化，生成一个UUID即可
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
    # 允许使用PLAINTEXT监听器，默认false，不建议在生产环境使用
      - ALLOW_PLAINTEXT_LISTENER=yes
    ### broker配置
    # 定义外网访问地址（宿主机ip地址和端口）
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://10.1.1.209:9492
    # broker.id，必须唯一
      - KAFKA_BROKER_ID=4
      - KAFKA_CFG_NODE_ID=4
    volumes:
      - ./kafka_3_data:/bitnami/kafka
  kafka-ui:
      image: provectuslabs/kafka-ui:latest
      networks:
        - kafka-net
      container_name: kafka-ui
      # restart: always
      ports:
        - 9091:8080
      environment:
        # 集群名称
        - KAFKA_CLUSTERS_0_NAME=local
        # 集群地址
        - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:9092,kafka2:9092,kafka3:9092,kafka4:9092

volumes:
  kafka_0_data:
    driver: local
  kafka_1_data:
    driver: local
  kafka_2_data:
    driver: local
  kafka_3_data:
    driver: local

networks:
  kafka-net:
    driver: bridge


# 生产环境版本，和开发环境主要注意公网ip的映射问题，需要好好考虑
# kafka1:
#    image: 'bitnami/kafka:3.3.1'
#    network_mode: mynetwork
#    container_name: kafka1
#    user: root
#    environment:
#    ### 通用配置
#    # 允许使用kraft，即Kafka替代Zookeeper
#     - KAFKA_ENABLE_KRAFT=yes
#    # kafka角色，做broker，也要做controller
#     - KAFKA_CFG_PROCESS_ROLES=broker,controller
#    # 指定供外部使用的控制类请求信息
#     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#    # 定义kafka服务端socket监听端口
#     - KAFKA_CFG_LISTENERS=PLAINTEXT://:17005,CONTROLLER://:9093
#    # 定义安全协议
#     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#    # 集群地址
#     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
#    # 允许使用PLAINTEXT监听器，默认false，不建议在生产环境使用
#     - ALLOW_PLAINTEXT_LISTENER=yes
#    # 设置broker最大内存，和初始内存
#     - KAFKA_HEAP_OPTS=-Xmx512M -Xms256M 
#    # 不允许自动创建主题
#     - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
#    # 使用Kafka时的集群id，集群内的Kafka都要用这个id做初始化，生成一个UUID即可
#     - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA
#    ### broker配置
#    # 定义外网访问地址（宿主机ip地址和端口）
#     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:17005
#    # broker.id，必须唯一
#     - KAFKA_BROKER_ID=1
#    volumes:
#     - /home/mycontainers/kafka1/kafka/kraft:/bitnami/kafka